name: Run the pipeline for pull requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  semantic-release:
    uses: Relinks/sawiday-github-actions/.github/workflows/workflow-semantic-release.yaml@v2.16.0
    permissions:
      contents: write
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
